### ISSUE TITLE
tag with # symbol not show

### ISSUE THREAD

**Issue by FelixHuoEZ** [hkgnp/electron-logseq-quicknote#1]
Capture contents:
[[https://github.com/hkgnp/electron-logseq-quicknote/issues/new][New Issue · hkgnp/electron-logseq-quicknote]] #test #test2

Show in logseq:
[[https://github.com/hkgnp/electron-logseq-quicknote/issues/new][New Issue · hkgnp/electron-logseq-quicknote]]

Tag not show in logseq.

**Comment by benjypng** [comment]
Thanks for reporting this. Please try the latest release (https://github.com/hkgnp/electron-logseq-quicknote/releases)

**Comment by FelixHuoEZ** [comment]
[0.0.8-alpha](https://github.com/hkgnp/electron-logseq-quicknote/releases/tag/v0.0.8-alpha) still not work

**Comment by benjypng** [comment]
Sorry please try 0.0.7

**Comment by FelixHuoEZ** [comment]
> Sorry please try 0.0.7

[0.0.7](https://github.com/hkgnp/electron-logseq-quicknote/releases/tag/v0.0.7) works, thanks.
